Imports

In [103]:
#Importando bibliotecas a serem usadas
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

Carregamento dos Dados

In [104]:
#Lendo os dados e criando do dataframe "df"
df = pd.read_csv("dados\dados_clientes.csv")
df.sample(5)

id  idade  renda_anual  pontuacao_gastos
202  203     58       117203                89
458  459     39        27239                93
459  460     39       144454                86
231  232     34       120843                14
491  492     36        85215                 9

Análise Exploratória

In [105]:
#Informações do dataframe, percebemos que não há nulos em nenhuma coluna
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                500 non-null    int64
 1   idade             500 non-null    int64
 2   renda_anual       500 non-null    int64
 3   pontuacao_gastos  500 non-null    int64
dtypes: int64(4)
memory usage: 15.8 KB


In [106]:
#Resumo estatístico das variáveis relevantes
df.iloc[:,1:4].describe().round(2)

idade  renda_anual  pontuacao_gastos
count  500.00       500.00            500.00
mean    44.73     81557.17             48.51
std     15.24     36764.38             29.56
min     18.00     20384.00              0.00
25%     32.00     49172.75             24.00
50%     45.00     79219.00             48.50
75%     57.00    113017.25             73.25
max     70.00    149695.00            100.00

Pré-Processamento

In [107]:
#Cria um padronizador
padronizador = StandardScaler()

In [108]:
#Padronizando as variáveis de interesse
df_padronizado = padronizador.fit_transform(df[["idade", "renda_anual", "pontuacao_gastos"]])

In [109]:
#Visualizando os dados
print(df_padronizado, type(df_padronizado))

[[ 0.74012478  0.35893538  1.40506904]
 [ 1.59401387  1.49192537  0.05039391]
 [ 0.08328703  0.13776654  0.45679645]
 ...
 [-0.31081563  0.32661636  0.18586143]
 [-1.23038848 -1.48706069  1.43893592]
 [-1.03333716 -0.96992912 -0.59307677]] <class 'numpy.ndarray'>


Construção do Modelo de Machine Learning Para Segmentação de Clientes

In [110]:
#Definindo o número de clusters (k)
k = 3
#Criando o modelo Kmeans
kmeans = KMeans (n_clusters=k)
#Treinamento do modelo com os dados padronizados
kmeans.fit(df_padronizado)
#Vamos criar um coluna para receber os clusters criados
df['cluster'] = kmeans.labels_

In [111]:
#Exibe o resultado da segmentação
df.head(10)

id  idade  renda_anual  pontuacao_gastos  cluster
0   1     56        94740                90        0
1   2     69       136352                50        2
2   3     46        86617                62        0
3   4     32       114841                97        0
4   5     60        36896                51        2
5   6     25       145729                37        1
6   7     38        66175                96        0
7   8     56        27805                87        0
8   9     36        25237                78        0
9  10     40       135247                29        1

In [112]:
#Salvar em planilha os resultados

df.to_csv('dados/segmentos.csv', index = False)